name: Build Virtualenv

on:
  push:
    branches:
      - "master"
  pull_request:

jobs:
  build-venv:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          push: false
          file: tools/docker/venv.Dockerfile
